version: "3.9"
services:
  web:
    build: .
    ports:
     - "5000:5000"
    
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      
      start_period: 40s
    
